import { defineObjectBindings } from "@liveroom-tech/react-immersive/utils";

export const objectBindings = defineObjectBindings({
  Object_2: {
    id: "object-2",
    modelObjectId: "Object_2",
    group: "shirt",
    tags: ["garment", "printable"],
    type: "other",
    label: "Object 2",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Object_3: {
    id: "object-3",
    modelObjectId: "Object_3",
    group: "shirt",
    tags: ["garment", "printable"],
    type: "other",
    label: "Object 3",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Object_4: {
    id: "object-4",
    modelObjectId: "Object_4",
    group: "shirt",
    tags: ["garment", "printable"],
    type: "other",
    label: "Object 4",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Object_5: {
    id: "object-5",
    modelObjectId: "Object_5",
    group: "shirt",
    tags: ["garment", "printable"],
    type: "other",
    label: "Object 5",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
});
