import { defineObjectBindings } from "@liveroom-tech/react-immersive/utils";

export const objectBindings = defineObjectBindings({
  Cylinder001_Material001_0: {
    id: "cylinder001-material001-0",
    modelObjectId: "Cylinder001_Material001_0",
    type: "other",
    label: "Cylinder001 Material001 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder001_Material002_0: {
    id: "cylinder001-material002-0",
    modelObjectId: "Cylinder001_Material002_0",
    type: "other",
    label: "Cylinder001 Material002 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder001_Material003_0: {
    id: "cylinder001-material003-0",
    modelObjectId: "Cylinder001_Material003_0",
    type: "other",
    label: "Cylinder001 Material003 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder001_Material004_0: {
    id: "cylinder001-material004-0",
    modelObjectId: "Cylinder001_Material004_0",
    type: "other",
    label: "Cylinder001 Material004 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder002_Material_0: {
    id: "cylinder002-material-0",
    modelObjectId: "Cylinder002_Material_0",
    type: "other",
    label: "Cylinder002 Material 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder002_Material005_0: {
    id: "cylinder002-material005-0",
    modelObjectId: "Cylinder002_Material005_0",
    type: "other",
    label: "Cylinder002 Material005 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder002_Material006_0: {
    id: "cylinder002-material006-0",
    modelObjectId: "Cylinder002_Material006_0",
    type: "other",
    label: "Cylinder002 Material006 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder002_Material007_0: {
    id: "cylinder002-material007-0",
    modelObjectId: "Cylinder002_Material007_0",
    type: "other",
    label: "Cylinder002 Material007 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder003_Material001_0: {
    id: "cylinder003-material001-0",
    modelObjectId: "Cylinder003_Material001_0",
    type: "other",
    label: "Cylinder003 Material001 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder003_Material011_0: {
    id: "cylinder003-material011-0",
    modelObjectId: "Cylinder003_Material011_0",
    type: "other",
    label: "Cylinder003 Material011 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder004_Material008_0: {
    id: "cylinder004-material008-0",
    modelObjectId: "Cylinder004_Material008_0",
    type: "other",
    label: "Cylinder004 Material008 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder005_Material001_0: {
    id: "cylinder005-material001-0",
    modelObjectId: "Cylinder005_Material001_0",
    type: "other",
    label: "Cylinder005 Material001 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder005_Material002_0: {
    id: "cylinder005-material002-0",
    modelObjectId: "Cylinder005_Material002_0",
    type: "other",
    label: "Cylinder005 Material002 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder005_Material003_0: {
    id: "cylinder005-material003-0",
    modelObjectId: "Cylinder005_Material003_0",
    type: "other",
    label: "Cylinder005 Material003 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder005_Material004_0: {
    id: "cylinder005-material004-0",
    modelObjectId: "Cylinder005_Material004_0",
    type: "other",
    label: "Cylinder005 Material004 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder006_Material_0: {
    id: "cylinder006-material-0",
    modelObjectId: "Cylinder006_Material_0",
    type: "other",
    label: "Cylinder006 Material 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder006_Material005_0: {
    id: "cylinder006-material005-0",
    modelObjectId: "Cylinder006_Material005_0",
    type: "other",
    label: "Cylinder006 Material005 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder006_Material006_0: {
    id: "cylinder006-material006-0",
    modelObjectId: "Cylinder006_Material006_0",
    type: "other",
    label: "Cylinder006 Material006 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder006_Material007_0: {
    id: "cylinder006-material007-0",
    modelObjectId: "Cylinder006_Material007_0",
    type: "other",
    label: "Cylinder006 Material007 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder007_Material001_0: {
    id: "cylinder007-material001-0",
    modelObjectId: "Cylinder007_Material001_0",
    type: "other",
    label: "Cylinder007 Material001 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder007_Material011_0: {
    id: "cylinder007-material011-0",
    modelObjectId: "Cylinder007_Material011_0",
    type: "other",
    label: "Cylinder007 Material011 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder008_Material008_0: {
    id: "cylinder008-material008-0",
    modelObjectId: "Cylinder008_Material008_0",
    type: "other",
    label: "Cylinder008 Material008 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder009_Material001_0: {
    id: "cylinder009-material001-0",
    modelObjectId: "Cylinder009_Material001_0",
    type: "other",
    label: "Cylinder009 Material001 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder009_Material002_0: {
    id: "cylinder009-material002-0",
    modelObjectId: "Cylinder009_Material002_0",
    type: "other",
    label: "Cylinder009 Material002 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder009_Material003_0: {
    id: "cylinder009-material003-0",
    modelObjectId: "Cylinder009_Material003_0",
    type: "other",
    label: "Cylinder009 Material003 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder009_Material004_0: {
    id: "cylinder009-material004-0",
    modelObjectId: "Cylinder009_Material004_0",
    type: "other",
    label: "Cylinder009 Material004 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder010_Material_0: {
    id: "cylinder010-material-0",
    modelObjectId: "Cylinder010_Material_0",
    type: "other",
    label: "Cylinder010 Material 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder010_Material005_0: {
    id: "cylinder010-material005-0",
    modelObjectId: "Cylinder010_Material005_0",
    type: "other",
    label: "Cylinder010 Material005 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder010_Material006_0: {
    id: "cylinder010-material006-0",
    modelObjectId: "Cylinder010_Material006_0",
    type: "other",
    label: "Cylinder010 Material006 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder010_Material007_0: {
    id: "cylinder010-material007-0",
    modelObjectId: "Cylinder010_Material007_0",
    type: "other",
    label: "Cylinder010 Material007 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder011_Material001_0: {
    id: "cylinder011-material001-0",
    modelObjectId: "Cylinder011_Material001_0",
    type: "other",
    label: "Cylinder011 Material001 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder011_Material011_0: {
    id: "cylinder011-material011-0",
    modelObjectId: "Cylinder011_Material011_0",
    type: "other",
    label: "Cylinder011 Material011 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder012_Material008_0: {
    id: "cylinder012-material008-0",
    modelObjectId: "Cylinder012_Material008_0",
    type: "other",
    label: "Cylinder012 Material008 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder017_Material001_0: {
    id: "cylinder017-material001-0",
    modelObjectId: "Cylinder017_Material001_0",
    type: "other",
    label: "Cylinder017 Material001 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder017_Material002_0: {
    id: "cylinder017-material002-0",
    modelObjectId: "Cylinder017_Material002_0",
    type: "other",
    label: "Cylinder017 Material002 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder017_Material003_0: {
    id: "cylinder017-material003-0",
    modelObjectId: "Cylinder017_Material003_0",
    type: "other",
    label: "Cylinder017 Material003 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder017_Material004_0: {
    id: "cylinder017-material004-0",
    modelObjectId: "Cylinder017_Material004_0",
    type: "other",
    label: "Cylinder017 Material004 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder018_Material_0: {
    id: "cylinder018-material-0",
    modelObjectId: "Cylinder018_Material_0",
    type: "other",
    label: "Cylinder018 Material 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder018_Material005_0: {
    id: "cylinder018-material005-0",
    modelObjectId: "Cylinder018_Material005_0",
    type: "other",
    label: "Cylinder018 Material005 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder018_Material006_0: {
    id: "cylinder018-material006-0",
    modelObjectId: "Cylinder018_Material006_0",
    type: "other",
    label: "Cylinder018 Material006 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder018_Material007_0: {
    id: "cylinder018-material007-0",
    modelObjectId: "Cylinder018_Material007_0",
    type: "other",
    label: "Cylinder018 Material007 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder019_Material001_0: {
    id: "cylinder019-material001-0",
    modelObjectId: "Cylinder019_Material001_0",
    type: "other",
    label: "Cylinder019 Material001 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder019_Material011_0: {
    id: "cylinder019-material011-0",
    modelObjectId: "Cylinder019_Material011_0",
    type: "other",
    label: "Cylinder019 Material011 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder020_Material008_0: {
    id: "cylinder020-material008-0",
    modelObjectId: "Cylinder020_Material008_0",
    type: "other",
    label: "Cylinder020 Material008 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder021_Material001_0: {
    id: "cylinder021-material001-0",
    modelObjectId: "Cylinder021_Material001_0",
    type: "other",
    label: "Cylinder021 Material001 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder021_Material002_0: {
    id: "cylinder021-material002-0",
    modelObjectId: "Cylinder021_Material002_0",
    type: "other",
    label: "Cylinder021 Material002 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder021_Material003_0: {
    id: "cylinder021-material003-0",
    modelObjectId: "Cylinder021_Material003_0",
    type: "other",
    label: "Cylinder021 Material003 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder021_Material004_0: {
    id: "cylinder021-material004-0",
    modelObjectId: "Cylinder021_Material004_0",
    type: "other",
    label: "Cylinder021 Material004 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder022_Material_0: {
    id: "cylinder022-material-0",
    modelObjectId: "Cylinder022_Material_0",
    type: "other",
    label: "Cylinder022 Material 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder022_Material005_0: {
    id: "cylinder022-material005-0",
    modelObjectId: "Cylinder022_Material005_0",
    type: "other",
    label: "Cylinder022 Material005 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder022_Material006_0: {
    id: "cylinder022-material006-0",
    modelObjectId: "Cylinder022_Material006_0",
    type: "other",
    label: "Cylinder022 Material006 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder022_Material007_0: {
    id: "cylinder022-material007-0",
    modelObjectId: "Cylinder022_Material007_0",
    type: "other",
    label: "Cylinder022 Material007 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder023_Material001_0: {
    id: "cylinder023-material001-0",
    modelObjectId: "Cylinder023_Material001_0",
    type: "other",
    label: "Cylinder023 Material001 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder023_Material011_0: {
    id: "cylinder023-material011-0",
    modelObjectId: "Cylinder023_Material011_0",
    type: "other",
    label: "Cylinder023 Material011 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder024_Material008_0: {
    id: "cylinder024-material008-0",
    modelObjectId: "Cylinder024_Material008_0",
    type: "other",
    label: "Cylinder024 Material008 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder033_Material001_0: {
    id: "cylinder033-material001-0",
    modelObjectId: "Cylinder033_Material001_0",
    type: "other",
    label: "Cylinder033 Material001 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder033_Material002_0: {
    id: "cylinder033-material002-0",
    modelObjectId: "Cylinder033_Material002_0",
    type: "other",
    label: "Cylinder033 Material002 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder033_Material003_0: {
    id: "cylinder033-material003-0",
    modelObjectId: "Cylinder033_Material003_0",
    type: "other",
    label: "Cylinder033 Material003 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder033_Material004_0: {
    id: "cylinder033-material004-0",
    modelObjectId: "Cylinder033_Material004_0",
    type: "other",
    label: "Cylinder033 Material004 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder034_Material_0: {
    id: "cylinder034-material-0",
    modelObjectId: "Cylinder034_Material_0",
    type: "other",
    label: "Cylinder034 Material 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder034_Material005_0: {
    id: "cylinder034-material005-0",
    modelObjectId: "Cylinder034_Material005_0",
    type: "other",
    label: "Cylinder034 Material005 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder034_Material006_0: {
    id: "cylinder034-material006-0",
    modelObjectId: "Cylinder034_Material006_0",
    type: "other",
    label: "Cylinder034 Material006 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder034_Material007_0: {
    id: "cylinder034-material007-0",
    modelObjectId: "Cylinder034_Material007_0",
    type: "other",
    label: "Cylinder034 Material007 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder035_Material001_0: {
    id: "cylinder035-material001-0",
    modelObjectId: "Cylinder035_Material001_0",
    type: "other",
    label: "Cylinder035 Material001 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder035_Material011_0: {
    id: "cylinder035-material011-0",
    modelObjectId: "Cylinder035_Material011_0",
    type: "other",
    label: "Cylinder035 Material011 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder036_Material008_0: {
    id: "cylinder036-material008-0",
    modelObjectId: "Cylinder036_Material008_0",
    type: "other",
    label: "Cylinder036 Material008 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder037_Material001_0: {
    id: "cylinder037-material001-0",
    modelObjectId: "Cylinder037_Material001_0",
    type: "other",
    label: "Cylinder037 Material001 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder037_Material002_0: {
    id: "cylinder037-material002-0",
    modelObjectId: "Cylinder037_Material002_0",
    type: "other",
    label: "Cylinder037 Material002 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder037_Material003_0: {
    id: "cylinder037-material003-0",
    modelObjectId: "Cylinder037_Material003_0",
    type: "other",
    label: "Cylinder037 Material003 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder037_Material004_0: {
    id: "cylinder037-material004-0",
    modelObjectId: "Cylinder037_Material004_0",
    type: "other",
    label: "Cylinder037 Material004 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder038_Material_0: {
    id: "cylinder038-material-0",
    modelObjectId: "Cylinder038_Material_0",
    type: "other",
    label: "Cylinder038 Material 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder038_Material005_0: {
    id: "cylinder038-material005-0",
    modelObjectId: "Cylinder038_Material005_0",
    type: "other",
    label: "Cylinder038 Material005 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder038_Material006_0: {
    id: "cylinder038-material006-0",
    modelObjectId: "Cylinder038_Material006_0",
    type: "other",
    label: "Cylinder038 Material006 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder038_Material007_0: {
    id: "cylinder038-material007-0",
    modelObjectId: "Cylinder038_Material007_0",
    type: "other",
    label: "Cylinder038 Material007 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder039_Material001_0: {
    id: "cylinder039-material001-0",
    modelObjectId: "Cylinder039_Material001_0",
    type: "other",
    label: "Cylinder039 Material001 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder039_Material011_0: {
    id: "cylinder039-material011-0",
    modelObjectId: "Cylinder039_Material011_0",
    type: "other",
    label: "Cylinder039 Material011 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder040_Material008_0: {
    id: "cylinder040-material008-0",
    modelObjectId: "Cylinder040_Material008_0",
    type: "other",
    label: "Cylinder040 Material008 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder041_Material001_0: {
    id: "cylinder041-material001-0",
    modelObjectId: "Cylinder041_Material001_0",
    type: "other",
    label: "Cylinder041 Material001 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder041_Material002_0: {
    id: "cylinder041-material002-0",
    modelObjectId: "Cylinder041_Material002_0",
    type: "other",
    label: "Cylinder041 Material002 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder041_Material003_0: {
    id: "cylinder041-material003-0",
    modelObjectId: "Cylinder041_Material003_0",
    type: "other",
    label: "Cylinder041 Material003 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder041_Material004_0: {
    id: "cylinder041-material004-0",
    modelObjectId: "Cylinder041_Material004_0",
    type: "other",
    label: "Cylinder041 Material004 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder042_Material_0: {
    id: "cylinder042-material-0",
    modelObjectId: "Cylinder042_Material_0",
    type: "other",
    label: "Cylinder042 Material 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder042_Material005_0: {
    id: "cylinder042-material005-0",
    modelObjectId: "Cylinder042_Material005_0",
    type: "other",
    label: "Cylinder042 Material005 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder042_Material006_0: {
    id: "cylinder042-material006-0",
    modelObjectId: "Cylinder042_Material006_0",
    type: "other",
    label: "Cylinder042 Material006 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder042_Material007_0: {
    id: "cylinder042-material007-0",
    modelObjectId: "Cylinder042_Material007_0",
    type: "other",
    label: "Cylinder042 Material007 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder043_Material001_0: {
    id: "cylinder043-material001-0",
    modelObjectId: "Cylinder043_Material001_0",
    type: "other",
    label: "Cylinder043 Material001 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder043_Material011_0: {
    id: "cylinder043-material011-0",
    modelObjectId: "Cylinder043_Material011_0",
    type: "other",
    label: "Cylinder043 Material011 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder044_Material008_0: {
    id: "cylinder044-material008-0",
    modelObjectId: "Cylinder044_Material008_0",
    type: "other",
    label: "Cylinder044 Material008 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder045_Material001_0: {
    id: "cylinder045-material001-0",
    modelObjectId: "Cylinder045_Material001_0",
    type: "other",
    label: "Cylinder045 Material001 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder045_Material002_0: {
    id: "cylinder045-material002-0",
    modelObjectId: "Cylinder045_Material002_0",
    type: "other",
    label: "Cylinder045 Material002 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder045_Material003_0: {
    id: "cylinder045-material003-0",
    modelObjectId: "Cylinder045_Material003_0",
    type: "other",
    label: "Cylinder045 Material003 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder045_Material004_0: {
    id: "cylinder045-material004-0",
    modelObjectId: "Cylinder045_Material004_0",
    type: "other",
    label: "Cylinder045 Material004 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder046_Material_0: {
    id: "cylinder046-material-0",
    modelObjectId: "Cylinder046_Material_0",
    type: "other",
    label: "Cylinder046 Material 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder046_Material005_0: {
    id: "cylinder046-material005-0",
    modelObjectId: "Cylinder046_Material005_0",
    type: "other",
    label: "Cylinder046 Material005 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder046_Material006_0: {
    id: "cylinder046-material006-0",
    modelObjectId: "Cylinder046_Material006_0",
    type: "other",
    label: "Cylinder046 Material006 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder046_Material007_0: {
    id: "cylinder046-material007-0",
    modelObjectId: "Cylinder046_Material007_0",
    type: "other",
    label: "Cylinder046 Material007 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder047_Material001_0: {
    id: "cylinder047-material001-0",
    modelObjectId: "Cylinder047_Material001_0",
    type: "other",
    label: "Cylinder047 Material001 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder047_Material011_0: {
    id: "cylinder047-material011-0",
    modelObjectId: "Cylinder047_Material011_0",
    type: "other",
    label: "Cylinder047 Material011 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
  Cylinder048_Material008_0: {
    id: "cylinder048-material008-0",
    modelObjectId: "Cylinder048_Material008_0",
    type: "other",
    label: "Cylinder048 Material008 0",
    status: "normal",
    selectable: true,
    hoverable: true,
    visible: true,
    style: {},
    actions: [
      {
        id: "change-color",
        label: "Change Color",
        type: "command",
      },
      {
        id: "change-material",
        label: "Change Material",
        type: "command",
      },
      {
        id: "toggle-visibility",
        label: "Toggle Visibility",
        type: "command",
      },
    ],
    metrics: {},
    metadata: {},
  },
});
