export default {
  "use-viewer-selection": "useViewerSelection",
  "use-viewer-hover": "useViewerHover",
  "use-viewer-model": "useViewerModel",
  "use-viewer-camera": "useViewerCamera",
  "use-viewer-connection": "useViewerConnection",
  "use-viewer-animations": "useViewerAnimations",
  "use-viewer-effects": "useViewerEffects",
  "use-viewer-actions": "useViewerActions",
  "use-object-binding": "useObjectBinding",
  "use-object-binding-ids": "useObjectBindingIds",
  "use-object-bindings": "useObjectBindings",
  "use-scene-config": "useSceneConfig",
  "use-shareable-viewer-state": "useShareableViewerState",
};
